### ISSUE TITLE
Rename the error issue about dropping chunk

### ISSUE THREAD

**Issue by rmchurch** [rkube/delta#30]
This line appears to not be accurate, the chunk is still sent on if the normalization is not available
https://github.com/rkube/delta/blob/d820a82f011ff5a0952bf9ef0bc5cbe012ac98cf/delta/data_models/helpers.py#L88

**Comment by rkube** [comment]
Thanks, it has been replaced with a more helpful message:
```python
self.logger.info(f"new_chunk: {chunk_idx}: self.normalize has not been initialized")
```
