### ISSUE TITLE
Settle on config files

### ISSUE THREAD

**Issue by rmchurch** [rkube/delta#6]
We need to settle on common structure and variables for config files.

**Comment by rkube** [comment]
Let's do this in combination with unit tests.
In pytest we can configure a module-wide fixture, basically a static configuration dictionary, that will be used by all
unit tests: https://docs.pytest.org/en/stable/fixture.html#fixtures-a-prime-example-of-dependency-injection
This serves can serve as a frozen configuration file syntax against which all code that uses the configuration file will be tested.

**Comment by rkube** [comment]
conftest.py now serves a configuration file as a test fixture.
