### ISSUE TITLE
Setup test_performance area for simple setups to run performance tests

### ISSUE THREAD

**Issue by rmchurch** [rkube/delta#7]
Create test_performance folder, put in README and necessary config files for a simple setup to test network performance.

**Comment by rkube** [comment]
I added a tests_performance folder

**Comment by rkube** [comment]
I am adding a lot of files here - these should not be in the repo. I suggest we start putting a performance test section in the wiki.

**Comment by rmchurch** [comment]
Ralph, I think this test_performance folder should NOT have performance
logs (as you say, can put in a wiki), but rather instructions, config
files, etc. needed to run a realistic end-to-end case for Jason to begin
performance testing.

**Comment by rmchurch** [comment]
I'm hoping later today to put in the stuff to run receiver_brute_mpi, and
update the generator to enable the end-to-end workflow.

**Comment by rkube** [comment]
Got it. I started putting some benchmark results in the wiki and will delete any performance logs from tests_performance.
